/**
 * Beckn Core API
 * Beckn Core API specification
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Describes the ACK response
 */
export interface Ack {
  /**
   * Describe the status of the ACK response. If schema validation passes, status is ACK else it is NACK
   */
  status: Ack.StatusEnum;
}

export namespace Ack {
  export type StatusEnum = "ACK" | "NACK";
  export const StatusEnum = {
    Ack: "ACK" as StatusEnum,
    Nack: "NACK" as StatusEnum
  };
}


