/**
 * Beckn Core API
 * Beckn Core API specification
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Describes an address
 */
export class Address {
  /**
   * Door / Shop number of the address
   */
  door?: string;
  /**
   * Name of address if applicable. Example, shop name
   */
  name?: string;
  /**
   * Name of the building or block
   */
  building?: string;
  /**
   * Street name or number
   */
  street?: string;
  /**
   * Name of the locality, apartments
   */
  locality?: string;
  /**
   * Name or number of the ward if applicable
   */
  ward?: string;
  /**
   * City name
   */
  city?: string;
  /**
   * State name
   */
  state?: string;
  /**
   * Country name
   */
  country?: string;
  /**
   * Area code. This can be Pincode, ZIP code or any equivalent
   */
  area_code?: string;
}

