/**
 * Beckn Core API
 * Beckn Core API specification
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Descriptor } from "./Descriptor";
import { Time } from "./Time";

// import { Id } from './id';


/**
 * Describes a category
 */
export class Category {
  /**
   * Unique id of the category
   */
  id?: string;
  parent_category_id?: string;
  descriptor?: Descriptor;
  time?: Time;
  /**
   * Describes a tag. This is a simple key-value store which is used to contain extended metadata
   */
  tags?: { [key: string]: string; };
}

