/**
 * Beckn Core API
 * Beckn Core API specification
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Authorization } from "./authorization";
import { Descriptor } from "./Descriptor";
import { Time } from "./Time";
import { Person } from "./person";
import { Contact } from "./contact";
import { Location } from "./location";


/**
 * Details on the start of fulfillment
 */
export class FulfillmentDetails {
  private _location?: Location;

  get location(): Location {
    return this._location;
  }

  set location(value: Location) {
    this._location = value;
  }

  private _time?: Time;

  get time(): Time {
    return this._time;
  }

  set time(value: Time) {
    this._time = value;
  }

  private _instructions?: Descriptor;

  get instructions(): Descriptor {
    return this._instructions;
  }

  set instructions(value: Descriptor) {
    this._instructions = value;
  }

  private _contact?: Contact;

  get contact(): Contact {
    return this._contact;
  }

  set contact(value: Contact) {
    this._contact = value;
  }

  private _person?: Person;

  get person(): Person {
    return this._person;
  }

  set person(value: Person) {
    this._person = value;
  }

  private _authorization?: Authorization;

  get authorization(): Authorization {
    return this._authorization;
  }

  set authorization(value: Authorization) {
    this._authorization = value;
  }
}

