/**
 * Beckn Core API
 * Beckn Core API specification
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Price } from "./price";
import { Descriptor } from "./Descriptor";
import { Time } from "./Time";


/**
 * Describes an item. Allows for domain extension.
 */
export class Item {
  /**
   * This is the unique identifier of a service item. An example of an Item ID could be the SKU of a product.
   */
  private _id?: string;

  get id(): string {
    return this._id;
  }

  set id(value: string) {
    this._id = value;
  }

  private _parent_item_id?: string;

  get parent_item_id(): string {
    return this._parent_item_id;
  }

  set parent_item_id(value: string) {
    this._parent_item_id = value;
  }

  private _descriptor?: Descriptor;

  get descriptor(): Descriptor {
    return this._descriptor;
  }

  set descriptor(value: Descriptor) {
    this._descriptor = value;
  }

  private _price?: Price;

  get price(): Price {
    return this._price;
  }

  set price(value: Price) {
    this._price = value;
  }

  private _category_id?: string;

  get category_id(): string {
    return this._category_id;
  }

  set category_id(value: string) {
    this._category_id = value;
  }

  private _fulfillment_id?: string;

  get fulfillment_id(): string {
    return this._fulfillment_id;
  }

  set fulfillment_id(value: string) {
    this._fulfillment_id = value;
  }

  private _rating?: number;

  get rating(): number {
    return this._rating;
  }

  set rating(value: number) {
    this._rating = value;
  }

  private _location_id?: string;

  get location_id(): string {
    return this._location_id;
  }

  set location_id(value: string) {
    this._location_id = value;
  }

  private _time?: Time;

  get time(): Time {
    return this._time;
  }

  set time(value: Time) {
    this._time = value;
  }

  /**
   * If the entity can be rated or not
   */
  private _rateable?: boolean;

  get rateable(): boolean {
    return this._rateable;
  }

  set rateable(value: boolean) {
    this._rateable = value;
  }

  private _matched?: boolean;

  get matched(): boolean {
    return this._matched;
  }

  set matched(value: boolean) {
    this._matched = value;
  }

  private _related?: boolean;

  get related(): boolean {
    return this._related;
  }

  set related(value: boolean) {
    this._related = value;
  }

  private _recommended?: boolean;

  get recommended(): boolean {
    return this._recommended;
  }

  set recommended(value: boolean) {
    this._recommended = value;
  }

  /**
   * Describes a tag. This is a simple key-value store which is used to contain extended metadata
   */
  private _tags?: { [key: string]: string; };

  get tags(): { [p: string]: string } {
    return this._tags;
  }

  set tags(value: { [p: string]: string }) {
    this._tags = value;
  }
}


