/**
 * Beckn Core API
 * Beckn Core API specification
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Circle } from "./circle";
import { Address } from "./address";
import { Country } from "./Country";
import { Descriptor } from "./Descriptor";
import { Time } from "./Time";
import { City } from "./City";


/**
 * Describes the location of a runtime object.
 */
export class Location {
  private _3dspace?: string;

  private _id?: string;

  get id(): string {
    return this._id;
  }

  set id(value: string) {
    this._id = value;
  }

  private _descriptor?: Descriptor;

  get descriptor(): Descriptor {
    return this._descriptor;
  }

  set descriptor(value: Descriptor) {
    this._descriptor = value;
  }

  /**
   * Describes a gps coordinate
   */
  private _gps?: string;

  get gps(): string {
    return this._gps;
  }

  set gps(value: string) {
    this._gps = value;
  }

  private _address?: Address;

  get address(): Address {
    return this._address;
  }

  set address(value: Address) {
    this._address = value;
  }

  private _station_code?: string;

  get station_code(): string {
    return this._station_code;
  }

  set station_code(value: string) {
    this._station_code = value;
  }

  private _city?: City;

  get city(): City {
    return this._city;
  }

  set city(value: City) {
    this._city = value;
  }

  private _country?: Country;

  get country(): Country {
    return this._country;
  }

  set country(value: Country) {
    this._country = value;
  }

  private _circle?: Circle;

  get circle(): Circle {
    return this._circle;
  }

  set circle(value: Circle) {
    this._circle = value;
  }

  private _polygon?: string;

  get polygon(): string {
    return this._polygon;
  }

  set polygon(value: string) {
    this._polygon = value;
  }

  private _time?: Time;

  get time(): Time {
    return this._time;
  }

  set time(value: Time) {
    this._time = value;
  }
}

