/**
 * Beckn Core API
 * Beckn Core API specification
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiProperty } from "@nestjs/swagger";


export class PaymentParams {
  [key: string]: string | any;


  /**
   * This value will be placed in the the $transaction_id url param in case of http/get and in the requestBody http/post requests
   */
  transaction_id?: string;
  transaction_status?: string;

  @ApiProperty({ pattern: "[+-]?([0-9]*[.])?[0-9]+" })
  amount?: string;
  currency: string;
}

