pipeline {
    agent any
    tools { 
        maven 'mvn' 
    }
    stages {
        stage('Build') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn -B -DskipTests clean package'
                    } else {
                        bat 'mvn -B -DskipTests clean package'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn test'
                    } else {
                        bat 'mvn test'
                    }
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                script {
                    if (isUnix()) {
                        sh './jenkins/scripts/deliver.sh'
                    } else {
                        bat '.\\jenkins\\scripts\\deliver.bat'
                    }
                }
            }
        }
    }
}