pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // Navigate to the 'clients' folder
                dir('clients') {
                    // Run Maven build from the 'clients' folder
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                // Navigate to the 'clients' folder
                dir('clients') {
                    // Run Maven test from the 'clients' folder
                    sh 'mvn test'
                }
            }
            post {
                always {
                    // JUnit report from the 'clients' folder
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                // Run deliver.sh script from the project root
                sh './deliver.bat'
            }
        }
    }
}
